USE DREM_WITH_DATA;
CREATE TABLE STUDENT1(
ID int AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(50),
AGE INT,
GRADE VARCHAR(50)
);

INSERT INTO STUDENT1 ( NAME,age, grade) values('JOHN DOE', 20, 'A');
INSERT INTO STUDENT1 ( NAME, age,grade) VALUES ('JANE SMITH',22,'B');

SET SQL_SAFE_UPDATES=0; #DISABLE THE UPDATE MODE
UPDATE STUDENT1 SET grade ='A+' WHERE NAME = 'JOHN SMITH';
SET SQL_SAFE_UPDATES=1;

DELETE FROM STUDENT1 WHERE age<21;

CREATE TABLE EMPLOYEE(
EMPLOYEE_ID  INT AUTO_INCREMENT PRIMARY KEY,
EMPLOYEE_NAME VARCHAR(50), 
SALARY DECIMAL(10,2),
DEPARTMENT VARCHAR(50));

INSERT INTO EMPLOYEE(EMPLOYEE_NAME,SALARY,DEPARTMENT)
VALUES('JOHN DOE',60000,'FINACE'),
      ('JOHN SMITH',80000,'MARKETING');
      
INSERT INTO EMPLOYEE ( EMPLOYEE_NAME,SALARY,DEPARTMENT)
VALUES('ALICE JOHNSON',55000,'HR'),
       ('BOB SMITH',70000,'IB');

GRANT SELECT ,INSERT ON EMPLOYEE TO 'JOHN'@'LOCALHOST';
REVOKE INSERT ON EMPLOYEE FROM 'JOHN'@'LOCALHOST';

SELECT*FROM EMPLOYEE;

BEGIN;
UPDATE EMPLOYEE SET SALARY=SALARY +5000 WHERE DEPARTMENT ='IB';
commit;

BEGIN ;
UPDATE EMPLOYEE SET SALARY = SALARY +5000 WHERE DEPARTMENT ='HR';
SELECT* FROM EMPLOYEE;
ROLLBACK;


BEGIN;
UPDATE EMPLOYEE SET SALARY=SALARY +5000 WHERE DEPARTMENT ='FINANCE';
SAVEPOINT SP1; 


UPDATE EMPLOYEE SET SALARY = SALARY -5000 WHERE DEPARTMENT ='HR';
Rollback TO SP1; 
COMMIT;

SET TRANSACTION READ WRITE;
BEGIN; 
UPDATE EMPLOYEE SET SALARY = SALARY * 1.10 WHERE DEPARTMENT = 'IB';
COMMIT;

create TABLE SUPER30 (
ID INT NOT NULL,
LASTNAME VARCHAR(255) NOT NULL,
FIRSTNAME varchar(255) NOT NULL,
CLASS INT,
PRIMARY KEY (ID)
);

CREATE TABLE PERSON (
PERSON_ID INT NOT NULL PRIMARY KEY,
FIRSTNAME VARCHAR(255),
LASTNAME VARCHAR(255),
ADDRESS VARCHAR(255),
CITY VARCHAR(255)
);

CREATE TABLE ORDER1(
 ORDER_ID INT NOT NULL,
 ORDER_NUMBER INT NOT NULL,
 PERSON_ID INT,
 PRIMARY KEY (ORDER_ID),
 FOREIGN KEY(PERSON_ID) references PERSON (PERSON_ID)
 );
 
 