CREATE DATABASE DEMO1;
USE DEMO1; 

CREATE TABLE EMPLOYEE (
EMPLOYEE_ID INT PRIMARY KEY auto_increment,
NAME VARCHAR (50),
DEPARTMENT VARCHAR(50),
SALARY VARCHAR(50)
);

INSERT INTO EMPLOYEE (NAME, DEPARTMENT,SALARY)
VALUES
('SURAJ','ACCOUNT','10000'),
('RAHUL','SCINCE','20000'),
('RINA','SPORT','30000'),
('PAYAL','MATHMATICAL','40000'),
('KIRTI','AGRICULTURE','50000'),
('RAGHAV','POLY',60000);

SELECT * FROM EMPLOYEE;

SELECT EMPLOYEE_ID,NAME,SALARY,
CASE
WHEN SALARY >50000 THEN 'HIGH'
WHEN SALARY BETWEEN 50000 AND 30000 THEN 'MEDIUM'
ELSE 'LOW'
END AS SALARY_CATEGORY 
FROM EMPLOYEE;

# SPECIAL COLOUM
 SELECT EMPLOYEE_ID, NAME,DEPARTMENT,SALARY,
 CASE DEPARTMENT
 WHEN 'ACCOUNT' THEN SALARY *0.10
 WHEN 'SCINCE' THEN SALARY *0.15
 WHEN 'POLY'THEN SALARY *0.20
 WHEN 'SPORT' THEN SALARY *0.25
 ELSE 0
 END AS BONUS
 FROM EMPLOYEE;
 
 # ORDER BY IN CASE
 
 SELECT EMPLOYEE_ID, NAME , DEPARTMENT,SALARY FROM EMPLOYEE
 ORDER BY
 CASE DEPARTMENT 
 WHEN 'MATHMATICALY' THEN 1
 WHEN 'POLY' THEN 2
 WHEN 'SPORT' THEN 3
 WHEN 'ACCOUNT' THEN 4
 ELSE 5
 END;
 
 # PARTITION BY 
  SELECT EMPLOYEE_ID,NAME,DEPARTMENT,SALARY,
  SUM(SALARY) OVER (PARTITION BY DEPARTMENT) AS TOTAL_DEPARTMENT_WISE_SALARY
  FROM EMPLOYEE;
  
  # ROW_NO WISE SALARY - DESENDING WISE
  SELECT EMPLOYEE_ID,NAME,DEPARTMENT, SALARY,
  row_number()OVER(partition by DEPARTMENT order by SALARY desc)AS ROW_NUM
  FROM EMPLOYEE;
  
  # AVRAGE SALARY -DEPARTMENT WISE
  SELECT EMPLOYEE_ID,NAME,DEPARTMENT,SALARY,
  avg(SALARY)OVER(PARTITION BY DEPARTMENT ORDER BY SALARY) AS AVERAGE_SALARY 
  FROM EMPLOYEE;
  
  
  
  


