CREATE DATABASE SALEORDER;

USE SALEORDER;
CREATE TABLE CUSTOMER(
CUSTOMER_ID INT NOT NULL PRIMARY KEY,
CUSTOMER_FIRS_TNAME VARCHAR(50) NOT NULL,
CUSTOMER_LAST_NAME VARCHAR(50) NOT NULL,
CUSTOMER_ADDRESS VARCHAR (250) NOT NULL,
CUSTOMER_SUBSCRIBE VARCHAR(250) NOT NULL,
CUSTOMER_CITY VARCHAR(50) NOT NULL,
CUSTOMER_POSTCODE CHAR(4) NULL,
CUSTOMER_CONTACT CHAR(12) NULL
 );
 
 CREATE TABLE INVENTARY(
 INVENTARY_ID TINYINT NOT NULL PRIMARY KEY,
 INVENTARY_NAME  VARCHAR(250) NOT NULL,
 INVENTARY_DESCRIPTION VARCHAR(255) NULL
 );
 
 CREATE TABLE EMPLOYEE(
 EMPLOYEE_ID TINYINT NOT NULL PRIMARY KEY,
 EMPLOYEE_FIRST_NAME VARCHAR (50) NOT NULL,
 EMPLOYEE_LAST_NAME VARCHAR (50) NOT NULL,
 EMPLOYEE_XTENSION CHAR(4) NULL
 );
 
 CREATE TABLE SALES(
 SALE_ID TINYINT NOT NULL PRIMARY KEY,
 CUSTOMER_ID INT NOT NULL references CUSTOMER (CUSTOMER_ID),
 INVENTARY_ID TINYINT NOT NULL references INVENTARY (INVENTARY_ID),
 EMPLOYEE_ID TINYINT NOT NULL references EMPLOYEE(EMPLOYEE_ID),
 SALE_DATE DATE NOT NULL,
 SALE_QUANTITY INT NOT NULL,
 SALE_UNIT_PRICE decimal(10,2) NOT NULL
 );
 
 SELECT * FROM CUSTOMER;
 INSERT INTO CUSTOMER (CUSTOMER_ID ,CUSTOMER_FIRS_TNAME ,CUSTOMER_LAST_NAME ,CUSTOMER_ADDRESS ,
 CUSTOMER_SUBSCRIBE ,CUSTOMER_CITY ,CUSTOMER_POSTCODE ,CUSTOMER_CONTACT) 
VALUES 
(1,'HARSH', 'THAKARE', 'SELLO', 'YES','WARDHA', '4420', '914567656778'),
(2,'RITIK','GHODE','GURUDWARA', 'YES', 'NANDED','6000','124556765467'),
(3,'DIPALI','WAGHADE', 'NALWADI','NO','WARDHA','4402','126788897645'
);

SELECT * FROM CUSTOMER;

INSERT INTO CUSTOMER_BACKUP SELECT * FROM CUSTOMER;
SELECT * from CUSTOMER WHERE CUSTOMER_FIRST_NAME LIKE'H%';
 
 
 
 
 
 
 
 
 
 
 
