create database hr_analytics;
use  hr_analytics;
#Basic Queries
#1. Retrieve the list of employees who have left the company (Attrition = 'Yes').
select * from hr_analytics
where Attrition= 'yes';

alter table hr_analytics
rename column ï»¿EmpID to EMP_ID;

#2. Find the average age of employees in each department.
select Department,avg(Age)
from hr_analytics
group by Department;

#3. Identify employees with a JobSatisfaction rating of 4 and above.
select *  
from hr_analytics
where JobSatisfaction>=4;

#4. List all employees working in the "Research & Development" department.
select * 
from hr_analytics
where Department="Research & Development";

#5. Calculate the total MonthlyIncome generated by employees in each JobRole.
select JobRole,sum(MonthlyIncome)as total_income
from hr_analytics
group by JobRole;


#Aggregations
#6. Find the total number of employees in each AgeGroup.
select AgeGroup, count(*) as total_employee
from hr_analytics
group by AgeGroup;

#7. Calculate the average PercentSalaryHike for employees who work overtime (OverTime = 'Yes').
select avg(PercentSalaryHike)as avg_percent_salary_hike
from hr_analytics
where overtime='yes';

#8. Determine the maximum TotalWorkingYears of employees in the company.
select max(TotalWorkingYears)as max_total_working_year
from hr_analytics;

#9. Find the department with the highest average EnvironmentSatisfaction rating.
select Department,avg(EnvironmentSatisfaction) as avg_envi_satis
from hr_analytics
group by Department
order by 'EnvironmentSatisfaction' desc
limit 1;

#10. Identify the average YearsAtCompany for employees grouped by their EducationField.
select EducationField,avg(YearsAtCompany) as avg_year_company
from hr_analytics
group by EducationField;


#Filtering and Sorting
#11. List the top 10 highest-paid employees based on their MonthlyIncome.
select EMP_ID,MonthlyIncome
from hr_analytics
order by MonthlyIncome desc
limit 10;


# 12. Find employees who have worked in more than 3 companies (NumCompaniesWorked > 3).
select EMP_ID,NumCompaniesWorked
from hr_analytics
where NumCompaniesWorked>3;

#13. Retrieve the names of employees who are in the highest JobLevel and belong to the "Sales" department.
select EMP_ID,JobLevel,Department
from hr_analytics
where JobLevel=( select max(JobLevel) from hr_analytics)
and Department='sales';


#14. Identify employees who received a PercentSalaryHike greater than the company's average.
select EMP_ID,PercentSalaryHike
from hr_analytics
where PercentSalaryHike>(select avg(PercentSalaryHike) from hr_analytics);

# 15. List employees with the least DistanceFromHome in each MaritalStatus category.
select EMP_ID,DistanceFromHome,MaritalStatus
from hr_analytics
where
(MaritalStatus,DistanceFromHome) in (select MaritalStatus,min(DistanceFromHome)
from  hr_analytics
group by MaritalStatus);


#Date-Based Analysis
#16. Calculate the total TrainingTimesLastYear for employees grouped by AgeGroup.
select AgeGroup,sum(TrainingTimesLastYear)as total_TrainingTimesLastYear
from hr_analytics
group by AgeGroup;

#17. Determine the average number of years employees have been in their current role (YearsInCurrentRole) for each JobRole.
select JobRole, avg(YearsInCurrentRole) as avg_YearsInCurrentRole
from hr_analytics
group by JobRole;

#18. Identify employees who have not received a promotion (YearsSinceLastPromotion = 0) in the last 5 years.
select EMP_ID,JobRole,YearsSinceLastPromotion
from hr_analytics
where YearsSinceLastPromotion = 0
and YearsAtCompany> 5;

#19. Find employees who have worked with their current manager (YearsWithCurrManager) for more than 10 years.
select EMP_ID,JobRole,Department,YearsWithCurrManager
from hr_analytics
where YearsWithCurrManager>10;

#20. List employees with YearsAtCompany greater than the average working years in the company.
select EMP_ID,Department,YearsAtCompany
from hr_analytics
where 
YearsAtCompany>(select avg(YearsAtCompany) from hr_analytics);

#Joins and Subqueries
#21. Identify the JobRole with the highest average MonthlyIncome.
select JobRole, avg(MonthlyIncome) as avg_MonthlyIncome
from hr_analytics 
group by JobRole
order by avg_MonthlyIncome desc
limit 1;

#22. Retrieve the JobSatisfaction and RelationshipSatisfaction scores of employees whose EnvironmentSatisfaction is below the average.
select JobSatisfaction,RelationshipSatisfaction,EnvironmentSatisfaction
from hr_analytics 
where 
EnvironmentSatisfaction < (select avg(EnvironmentSatisfaction) from hr_analytics) ;

#23. Find the department where employees have the highest PerformanceRating.
select Department,max(PerformanceRating)as max_performn_rating
from hr_analytics 
group by Department
order by max_performn_rating desc
limit 1;

#24. List all EducationField categories where employees have a JobInvolvement score of 3 or higher.
select  distinct EducationField 
from hr_analytics 
where JobInvolvement>=3;


#25. Identify employees in the top 5% of MonthlyIncome who also work overtime.
WITH ranked_incomes AS (
    SELECT 
        EMP_ID,
        MonthlyIncome,
        OverTime,  -- Adding OverTime column
        RANK() OVER (ORDER BY MonthlyIncome DESC) AS rank1,
        COUNT(*) OVER () AS total_count
    FROM hr_analytics
    WHERE OverTime = 'Yes'  -- Filter to only include employees with OverTime = 'Yes'
)
SELECT EMP_ID, MonthlyIncome, OverTime
FROM ranked_incomes
WHERE rank1 <= (total_count * 0.05);

#Advanced Analysis
#26. Calculate the attrition rate (Attrition = 'Yes') for each department.
select Department,
round((sum(case when Attrition='yes' then 1 else 0 end)/count(*))*100,2)
as attriation_rate
from hr_analytics
group by Department;

#27. Determine the correlation between DistanceFromHome and Attrition.
SELECT 
    (SUM((CAST(Attrition = 'Yes' AS UNSIGNED) - (SELECT AVG(CAST(Attrition = 'Yes' AS UNSIGNED)) FROM  hr_analytics )) * 
        (DistanceFromHome - (SELECT AVG(DistanceFromHome) FROM  hr_analytics )))) /
    (STDDEV_POP(CAST(Attrition = 'Yes' AS UNSIGNED)) * STDDEV_POP(DistanceFromHome)) AS correlation
FROM  hr_analytics  ;




#28. Analyze the average JobSatisfaction of employees who work overtime compared to those who do not.
select OverTime,avg(JobSatisfaction)
from hr_analytics 
group by OverTime;

#29. Find employees who have StockOptionLevel greater than 1 and are in SalarySlab = 'High'.
select EMP_ID,StockOptionLevel,SalarySlab
from hr_analytics
where StockOptionLevel>1
and SalarySlab='High';

#30. Identify the factors that differentiate employees with a PerformanceRating of 4 from others.
select PerformanceRating,avg(Age)as avg_age,
avg(JobSatisfaction)as avg_jobsatisfaction,
avg(YearsAtCompany)as avg_yearsatcompany,
count(OverTime)as count_overtime,
avg(DistanceFromHome)as avg_distancefromhome
from hr_analytics
group by PerformanceRating
having PerformanceRating=4 or PerformanceRating !=4;
















